# Generated by Django 3.2.12 on 2023-08-25 21:42
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokemonItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image_link", models.URLField()),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
